sonar.projectKey=renatobardi_the-loop_web
sonar.projectName=The Loop - Web
sonar.projectVersion=1.0.0
sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=coverage/coverage-final.json
