#!/usr/bin/env python3
"""Convert JSON rules from API to Semgrep YAML format."""

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path
from typing import Any


def json_to_semgrep_yaml(rules_json: dict[str, Any]) -> str:
    """Convert API JSON rules to Semgrep YAML format.

    Args:
        rules_json: Dictionary with 'rules' array from API response.

    Returns:
        Valid Semgrep YAML string.

    Raises:
        ValueError: If schema validation fails (missing keys, duplicates, etc).
    """
    # Validate schema
    if "rules" not in rules_json:
        raise ValueError("Missing 'rules' key in JSON input")

    rules = rules_json["rules"]
    if not isinstance(rules, list):
        raise ValueError("'rules' must be a list")

    if len(rules) == 0:
        raise ValueError("'rules' array is empty")

    # Check for duplicate rule IDs
    seen_ids: set[str] = set()
    for rule in rules:
        if "id" not in rule:
            raise ValueError("Rule missing required 'id' field")

        rule_id = rule["id"]
        if not isinstance(rule_id, str):
            raise ValueError(f"Rule 'id' must be string, got {type(rule_id).__name__}")

        if rule_id in seen_ids:
            raise ValueError(f"Duplicate rule ID detected: '{rule_id}'")

        seen_ids.add(rule_id)

    # Validate required fields in each rule
    for rule in rules:
        rule_id = rule["id"]
        required = ["languages", "message", "severity", "patterns"]
        for field in required:
            if field not in rule:
                raise ValueError(f"Rule '{rule_id}' missing required field: '{field}'")

    # Generate YAML
    yaml_lines = [
        "# theloop-rules.yml",
        "# Generated by The Loop — https://loop.oute.pro",
        f"# Version: {rules_json.get('version', '0.2.0')}",
        f"# Updated: {datetime.now().isoformat()}",
        "",
        "rules:",
    ]

    for rule in rules:
        yaml_lines.extend(_rule_to_yaml(rule))

    return "\n".join(yaml_lines)


def _rule_to_yaml(rule: dict[str, Any]) -> list[str]:
    """Convert single rule dict to YAML format.

    Args:
        rule: Rule dictionary with id, languages, message, severity, etc.

    Returns:
        List of YAML lines for this rule.
    """
    lines: list[str] = []

    # Rule ID
    lines.append(f"  - id: {rule['id']}")

    # Languages
    langs = rule.get("languages", ["generic"])
    langs_str = "[" + ", ".join(langs) + "]"
    lines.append(f"    languages: {langs_str}")

    # Message (multiline, indented)
    lines.append("    message: |")
    message = rule.get("message", "")
    for msg_line in message.split("\n"):
        lines.append(f"      {msg_line}")

    # Severity
    lines.append(f"    severity: {rule.get('severity', 'WARNING')}")

    # Metadata (if present)
    if "metadata" in rule:
        metadata = rule["metadata"]
        lines.append("    metadata:")
        for key, val in metadata.items():
            if isinstance(val, str):
                # Quote strings, escape internal quotes
                val_escaped = val.replace('"', '\\"')
                lines.append(f"      {key}: \"{val_escaped}\"")
            elif isinstance(val, list):
                # Format lists
                val_str = "[" + ", ".join(str(v) for v in val) + "]"
                lines.append(f"      {key}: {val_str}")
            else:
                lines.append(f"      {key}: {val}")

    # Patterns
    if "patterns" in rule:
        patterns = rule["patterns"]
        lines.append("    patterns:")

        if isinstance(patterns, list):
            for pattern in patterns:
                if isinstance(pattern, dict):
                    # Pattern is dict (e.g., {"pattern": "...", "pattern-either": [...]})
                    for key, val in pattern.items():
                        if key == "pattern":
                            lines.append(f"      - pattern: {val}")
                        elif key == "pattern-either":
                            lines.append("      - pattern-either:")
                            for alt in val:
                                lines.append(f"          - pattern: {alt}")
                        elif key == "pattern-not":
                            lines.append("      - pattern-not:")
                            for neg in val:
                                lines.append(f"          - pattern: {neg}")
                        elif key == "pattern-regex":
                            lines.append(f"      - pattern-regex: '{val}'")
                else:
                    # Pattern is string
                    lines.append(f"      - pattern: {pattern}")
        elif isinstance(patterns, dict):
            # Single pattern object
            for key, val in patterns.items():
                if key == "pattern":
                    lines.append(f"      - pattern: {val}")
                elif key == "pattern-either":
                    lines.append("      - pattern-either:")
                    for alt in val:
                        lines.append(f"          - pattern: {alt}")
                elif key == "pattern-not":
                    lines.append("      - pattern-not:")
                    for neg in val:
                        lines.append(f"          - pattern: {neg}")

    # Path exclusions (if present)
    if "paths" in rule:
        paths = rule["paths"]
        if "exclude" in paths:
            lines.append("    paths:")
            lines.append("      exclude:")
            for exclude in paths["exclude"]:
                lines.append(f"        - {exclude}")

    # Blank line between rules
    lines.append("")

    return lines


def main() -> None:
    """CLI entry point for json_to_semgrep_yaml utility."""
    parser = argparse.ArgumentParser(
        description="Convert JSON rules from The Loop API to Semgrep YAML format",
    )
    parser.add_argument(
        "--input",
        required=True,
        help="Input JSON file (from API)",
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Output YAML file (for semgrep)",
    )

    args = parser.parse_args()

    try:
        # Load JSON
        input_path = Path(args.input)
        if not input_path.exists():
            print(f"❌ Input file not found: {args.input}", file=sys.stderr)
            sys.exit(1)

        with open(input_path, encoding="utf-8") as f:
            rules_data = json.load(f)

        # Convert to YAML
        yaml_content = json_to_semgrep_yaml(rules_data)

        # Write output
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(yaml_content, encoding="utf-8")

        rule_count = len(rules_data.get("rules", []))
        print(f"✅ Converted {rule_count} rules → {args.output}")

    except FileNotFoundError as e:
        print(f"❌ File error: {e}", file=sys.stderr)
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"❌ Invalid JSON: {e}", file=sys.stderr)
        sys.exit(1)
    except ValueError as e:
        print(f"❌ Validation error: {e}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"❌ Unexpected error: {type(e).__name__}: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
