sonar.projectKey=renatobardi_the-loop_api
sonar.projectName=The Loop - API
sonar.projectVersion=1.0.0
sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=**/test_*.py,**/*_test.py
sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=coverage.xml
